### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by svranch**
Deleted outdated lines:

> You can find some more details in a nice writeup (though with old links and package names): http://iphonedevlog.wordpress.com/2014/04/07/installing-chris-brodys-sqlite-database-with-cordova-cli-android/.

This reference is outdated and gives many incorrect, out-dated, instructions. 

- Sandi

### CODE REVIEW

**Comment by brody2consult** [comment]
Thanks Sandi! Two things:

1: Can we identify a nice, understandable guide to replace the one to be removed?

I have seen some nice guides for people using Ionic, not sure about people using "normal" Cordova CLI.

2: I would like to remove it from the Cordova-sqlite-storage version first then merge it into this one. TODO for @brodybits is to document this workflow (somewhere).

This is marked as both a bug and a documentation TODO item.

**Comment by svranch** [comment]
Hi Chris - as usual - you are a very prompt responder... one reason you are good at what you do!  
 

===================================

> 1: Can we identify a nice, understandable guide to replace the one to be removed?

Actually, I was hoping you might know of one. So far, I have not found one. But if I do, I will post it here.  Plus - that link is secondary to your documentation which is super thorough, detailed, helpful, and full of tips and tricks.  That article is specifically focussed on "Brody's" sqlite cordova install.   Most ppl would probably prefer to find Specific BRODY SQLITE stuff on one of your websites anyway.  Perhaps in lieu of a new guide, we could insert text like so:
    

> {We are looking for links to helpful guides that are current. If you know of any, please send a message to BLAH BLAH} 

===================================

> 2. I would like to remove it from the Cordova-sqlite-storage version first then 

I did check Cordova-sqlite-storage README and I don't think it is in there. However, I could be wrong.   My thoughts were that it would be best to remove it NOW or at least strike it out. The reason is - to be quite honest with you - a newbie like me - which is who those kinds of guides as well as your README TIPS are geared towards - well I was confused by reading it.  It has alot of instructions that are weird and different to me.   It might seem easier for you to differentiate while reading that article - as you probably are familiar with the outdated stuff and can automatically skim right past it to more meaty stuff.   

And - if I might respectfully suggest - 
To leave it there for now until you can merge it later when you have time - or until we find a better link - is a discredit to the quality of your documentation.  In addition, you already have plenty of good helpful links and info in the README files. 

Those are my thoughts. But please feel free to do your own thing.  I won't mind a bit. Cuz you clearly are doing an excellent job of managing all of this!  Which is quite a challenge when you are doing alot of it out of the goodness of your heart. 

- Sandi

**Comment by brody2consult** [comment]
Hi @svranch,

Happy new year! I am now getting back to work after the celebrations and some needed exercise.

Thanks for your helpful words. I think you are absolutely right to remove the link which I did find in the common cordova-sqlite-storage version. I will remove it there, apply a couple minor fixes or so, and then merge into this version. I just raised litehelpers/Cordova-sqlite-storage#609 marked "community help" in case someone can contribute a good tutorial.

**Comment by brody2consult** [comment]
I removed the old tutorial from README.md in Cordova-sqlite-storage, added a newer tutorial (ref: litehelpers/Cordova-sqlite-storage#609), and merged these changes into this version. Thanks again!

**Pull request closed without merging**
